<?php

namespace ElislamBundle\Repository;

/**
 * BlogCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCatRepository extends \Doctrine\ORM\EntityRepository
{
}
