<?php

namespace ElislamBundle\Repository;

/**
 * Fos_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fos_userRepository extends \Doctrine\ORM\EntityRepository
{
}
