<?php

namespace ElislamBundle\Repository;

/**
 * GroepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroepRepository extends \Doctrine\ORM\EntityRepository
{
}
