<?php

namespace ElislamBundle\Repository;

/**
 * LesstofRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LesstofRepository extends \Doctrine\ORM\EntityRepository
{
}
