<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK8kitc0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK8kitc0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK8kitc0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK8kitc0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK8kitc0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'K8kitc0',
    'container.build_id' => '5a098171',
    'container.build_time' => 1531257506,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK8kitc0');
