<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF3xqmps\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF3xqmps/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF3xqmps.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF3xqmps\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF3xqmps\appDevDebugProjectContainer(array(
    'container.build_hash' => 'F3xqmps',
    'container.build_id' => '80fd5817',
    'container.build_time' => 1531258541,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerF3xqmps');
